"use client";

import { Building2, Settings, ShieldCheck, UserCircle } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

export default function SettingsPage() {
  const { user, activeProject } = useAuth();
  return <div className="page-container max-w-5xl">
    <div className="page-header"><div><p className="page-eyebrow">Account</p><h1 className="page-title">Profile & settings</h1><p className="page-description">Review your account and the workspace currently in use.</p></div></div>
    <div className="grid gap-6 md:grid-cols-[180px_minmax(0,1fr)]"><nav className="h-fit rounded-lg border border-card-border bg-card p-2" aria-label="Settings sections"><span className="flex items-center gap-2 rounded-md bg-accent/10 px-3 py-2 text-sm font-medium text-accent"><UserCircle size={16} />Profile</span><span className="mt-1 flex items-center gap-2 rounded-md px-3 py-2 text-sm text-foreground-muted"><Building2 size={16} />Workspace</span></nav><div className="space-y-4"><section className="panel p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-accent/15 text-accent"><UserCircle size={18} /></span><div><h2 className="text-base font-semibold">Profile</h2><p className="mt-0.5 text-sm text-foreground-muted">Your signed-in account.</p></div></div><dl className="mt-5 border-t border-card-border pt-4"><dt className="text-xs font-medium text-foreground-dim">Email address</dt><dd className="mt-1 text-sm text-foreground">{user?.email ?? "Account unavailable"}</dd></dl></section><section className="panel p-5"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-md bg-success/10 text-success"><ShieldCheck size={18} /></span><div><h2 className="text-base font-semibold">Active workspace</h2><p className="mt-0.5 text-sm text-foreground-muted">The project context applied to knowledge, sources, and integrations.</p></div></div><dl className="mt-5 grid gap-4 border-t border-card-border pt-4 sm:grid-cols-2"><div><dt className="text-xs font-medium text-foreground-dim">Workspace</dt><dd className="mt-1 text-sm text-foreground">{activeProject?.name ?? "No workspace selected"}</dd></div>{activeProject && <div><dt className="text-xs font-medium text-foreground-dim">Access role</dt><dd className="mt-1 text-sm text-foreground">{activeProject.role}</dd></div>}</dl></section><section className="rounded-lg border border-card-border bg-surface-elevated p-4"><div className="flex gap-3"><Settings size={17} className="mt-0.5 shrink-0 text-foreground-dim" /><p className="text-sm leading-5 text-foreground-muted">Additional workspace, integration, and security controls will appear here when they are available for your account.</p></div></section></div></div>
  </div>;
}
